frase = input('\033[31mDigite a Frase para Analisar: \033[m').strip()
palavra = frase.split()
print('A Primeira Palavra da sua Frase: ', palavra[0])
print('A Ultima Palavra da sua Frase: ', palavra[-1])
print('O Caractere com todas as Letras Maiúsculas: ', frase.upper())
print('O Caractere com todas as Letras Minúsculas: ', frase.lower())
print('Quantas Letras ao todo (Sem Considerar Espaços): ', len(frase.replace(" ", "")))
print('Quantas Letras tem a Primeira Palavra: ', len(frase.split()[0]))
print('A Frase começa com a palavra "SANTO": ', frase[:5].upper() == 'SANTO')
print('A Frase tem a Palavra "SILVA": ', ("SILVA" in frase.upper()))
print('Quantas Letras "A" tem no Texto: ', frase.upper().count('A'))
print('Em que Posição aparece a Letra "A" na primeira vez: ', frase.upper().find('A'))
print('Em que Posição aparece a Letra "A" na Ultima vez: ', frase.upper().rfind('A'), "\n")

numero = input('\033[32mDigite um número de 0 a 9999 para Analise:\033[m ')
print('Unidade: ', numero[3])
print('Dezena: ', numero[2])
print('Centena: ', numero[1])
print('Milhar: ', numero[0], "\n")

